url: https://stoneoakscouts.org
title: Stone Oak Scouts
imageurl: https://stoneoakscouts.org/images
exclude: ["README.md"]
kramdown:
  auto_ids: false
  smart_quotes: ["apos", "apos", "quot", "quot"]
  typographic_symbols:
    hellip: "..."
